### ISSUE TITLE
Display aliases in the embedded note title.

### ISSUE THREAD

**Issue by iris2jane** [snezhig/obsidian-front-matter-title#216]
![image](https://github.com/snezhig/obsidian-front-matter-title/assets/36763930/1ae4ba89-fd70-45ae-a875-72c1c7f2801a)

**Comment by Thundercraft5** [comment]
A css snippet to achieve this for now:
```css
/* Insert ::before in markdown embed */
.internal-embed.markdown-embed.inline-embed.is-loaded[alt]:not([src*="#"], [src*="^"])::before {
	content: attr(alt);
	align-items: center;
	display: flex;
	gap: var(--size-4-1);
	font-size: var(--font-text-size);
	font-weight: calc(var(--font-weight) + var(--bold-modifier));
	text-align: start;
	text-overflow: ellipsis;
	white-space: nowrap;
	padding: 0 0 var(--size-4-2) 0;
}

/* Hide original embed title */
.internal-embed.markdown-embed.inline-embed.is-loaded:not([src*="#"], [src*="^"]) > .embed-title.markdown-embed-title {
	display: none !important;
}
```
